"""智能立体车库上位机 - 配置常量"""

# 车库布局
NUM_LEVELS = 3
SPOTS_PER_LEVEL = 5
TOTAL_SPOTS = NUM_LEVELS * SPOTS_PER_LEVEL
LIFT_COLUMN = 2

# 费率
RATE_SMALL_PER_MINUTE = 0.20
RATE_LARGE_PER_MINUTE = 0.35
FREE_MINUTES = 15
MAX_DAILY_FEE_SMALL = 60.0
MAX_DAILY_FEE_LARGE = 100.0

# 网络
SERVER_HOST = "127.0.0.1"
SERVER_PORT = 9527

# 重连
RECONNECT_MAX_BACKOFF = 30.0
RECONNECT_BASE = 1.0

# GUI
SPOT_WIDTH = 100
SPOT_HEIGHT = 70
SPOT_PADDING = 8
CANVAS_PADDING = 20
